name: Create Release

on:
  create:
    tags:
      - 'yb-voyager/v*' # Trigger on any tag starting with 'yb-voyager/v'

jobs:
  build:
    name: Build Binary
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Build Binary
        run: |
          cd yb-voyager
          go build

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./yb-voyager/yb-voyager
          asset_name: yb-voyager
          asset_content_type: application/octet-stream
